### ISSUE TITLE
Author widget missing in 1.5.8

### ISSUE THREAD

**Issue by sdwheeler** [razonyang/hugo-theme-bootstrap#1044]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

I updated the theme to 1.5.8, moved the author configuration to `params.yaml`, and deleted `config/_default/author.yaml` as instructed. When I rebuild, the author widget is missing. If I restore the `author.yaml` file, the widget is restored but I still get the warning about deprecation.

- Related to: https://github.com/razonyang/hugo-theme-bootstrap/discussions/1041

### Steps to reproduce

1. Update theme to 1.5.8
2. Moved the author configuration to `params.yaml`
3. Delete `config/_default/author.yaml`
4. Rebuild

### Expected behavior

Author widget should be rendered in sidebar.

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of theme are you using?

github.com/razonyang/hugo-theme-bootstrap v1.5.8

### What version of Hugo are you using?

hugo v0.132.0-005e895a386e59dd38418066b3280fd98a33c96b+extended windows/amd64 BuildDate=2024-08-12T15:21:36Z VendorInfo=gohugoio

### What version of Node.js are you using?

v20.11.1

### What version of Git are you using?

git version 2.45.2.windows.1

### Additional context

go 1.22.6

You can view source code at https://github.com/sdwheeler/seanonit

**Comment by razonyang** [comment]
Hi, I noticed that you copied all of theme's files into your site, it's a wrong way to use a theme (except the case of customizing some templates), since the templates placed under your site get highest priority, so that theme's templates won't never be used.

It's easy to fix it, just remove site's scoped templates, then theme's templates will be used, in this case, you'll need to remove those  files from your site.

![image](https://github.com/user-attachments/assets/67209774-e1d5-4804-9ef4-ea17554c7598)

There may be same underlying issues in the next upgradation, I would suggest removing other theme's templates from your site, expect the modified/customized templates, so that your templates will keep up to date with theme.

**Comment by sdwheeler** [comment]
@razonyang Thanks, that fixed it. I made changes to 3 templates. I deleted all the templates that I didn't change and the author.yaml. It's working now.
