### ISSUE TITLE
Google AMP for Websites

### ISSUE THREAD

**Issue by itechf-s** [razonyang/hugo-theme-bootstrap#289]
**Is your feature request related to a problem? Please describe.**
google AMP

**Describe the solution you'd like**
Please add AMP support

**Describe alternatives you've considered**
Amp is google product, it will help to get organic traffic

**Additional context**
to get [more details](https://amp.dev/)

**Comment by razonyang** [comment]
I don't have experience about AMP, I skimmed through the documentation, there will be a lot of work.
And I'm worried about whether the styles are compatible. Therefore, this feature won't come very soon.

**Comment by razonyang** [comment]
I tried to implement AMP, but I encountered several obstacles and couldn't continue to work on it.

Styles cannot be used directly, because it exceeds the limit of AMP. And Bootstrap contains `!important` syntax, which is not allowed by AMP.

It's hard to solve it, and I'm not sure if it's worth to implement AMP for a blog site.

**Comment by razonyang** [comment]
I have no plans to implement this feature at present.
