### ISSUE TITLE
Docs: sort catalog

### ISSUE THREAD

**Issue by razonyang** [razonyang/hugo-theme-bootstrap#332]

**Comment by razonyang** [comment]
@sagarbehere FYI, it was implemented by 134da82. Now the catalog is sorted by weight(in descending order), and then sort the rest of pages without specifying weight by title in alphabetical order.

**Comment by sagarbehere** [comment]
@razonyang Yes, this is working great! Thank you :-)

**Comment by sagarbehere** [comment]
@razonyang Now that I have got some experience with the catalog sidebar, I think a minor adjustment is necessary: Let's sort the catalog sidebar by weight in **ascending** order (instead of the existing **descending** order), and then sort the rest of pages without specifying weight by title in alphabetical order. This requires changing only one word in `layouts/partials/docs/catalog.html`. In the line 
```
{{- range ($section.Pages.GroupBy "Weight" "desc") -}}
```
change `desc` to `asc`. Everything else stays the same.

The reason for this is that once you have a large number of pages and you want to order them in a certain way, it is easy to think of the first page you want in the order.. and assign it a low weight like 10. Then think of the next page you want in the sequence.. and give it a weight like 20.. the next page gets a weight 30.. and so on. And then the pages will appear in that order (if sorted by weight in **ascending** order). However, in the existing **descending** order, one needs to think in the opposite way: Think of the first page you want.. then give it some really high weight, like 100. Then for the next page, give a weight of 90.. and so on. But if you then realize that you have more than 10 pages.. oops.. you then need to go back and change the weights of all the previous pages.. that is annoying and not very user-friendly :)

**Comment by razonyang** [comment]
@sagarbehere I've thought about it before, but the weight pages will always behide the non-weight pages. That is because there is a default value in golang struct, that is, actually non-weight pages have a default value `0`.

**Comment by sagarbehere** [comment]
@razonyang Oh! Okay, in that case the existing settings make more sense. No changes needed. Thank you for clarifying.
