### ISSUE TITLE
article image not referenced correctly in Twitter card and open graph

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#368]
**Describe the bug**
Front matter is:
`
images:
  - images/2022-02-03-blog-im-texteditor-schreiben.png
`
Results:
- Article image in the list of posts and correctly referenced: `https://blog.natenom.com/2022/01/umzug-des-blogs-von-wordpress-zu-hugo-teil-1/images/2022-02-03-blog-im-texteditor-schreiben.png`
But in twitter card and open graph of this article it is referenced as `<meta name=twitter:image content="https://blog.natenom.com/images/2022-02-03-blog-im-texteditor-schreiben.png">`

**To Reproduce**
Define at least one image in images in Front Matter

**Expected behavior**
Should link the correct URL.

You can see this example: https://blog.natenom.com/

**Comment by razonyang** [comment]
I take a close look at the Hugo [internal twitter card template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html), it won't treat the `images`  as a page resource.

Image Lookup Order:

- `images` parameter: page resources are not supported, those images are related to the `static` folder if no absolute URL provided.
- Featured images matched by name with the pattern `*feature*`, such as `feature.png`.
- Cover or thumbnail images matched by name with the pattern `*thumbnail*` or `**cover**`, such as `cover.png` and `thumbnail.png`.

But current design conflicts with Hugo internal template. Although we can maintain our own version of twitter card template, it would be painful when users switch from this theme to others. IMO, the images in the list should follow the same rules. So that users can change theme without pain in the future.

What do you think? @Natenom @chrisrummel

**Comment by chrisrummel** [comment]
Is this only about the twitter card template? Or about list pages, too?
If the only thing I need to do, is create a 180px wide version of my picture named `feature.png` to make all list pages use this file, I can live with that.

**Comment by razonyang** [comment]
@chrisrummel It'll impact the covers on post's list after fixing it, so the `images` parameter need to be deleted too if there is a page resource was included.
