### ISSUE TITLE
How to shut down service worker?

### ISSUE THREAD

**Issue by Y4er** [razonyang/hugo-theme-bootstrap#524]
My blog is hosted on vercel. Since there is only 100g of traffic per month, and enabling service worker will request each picture, the traffic will be used very fast, so is there any way to turn off service worker?

Thank you.

**Comment by razonyang** [comment]
Yes, you can turn it off by removing the `[pwa]` block from `params.toml`.

```
[pwa]
  ...
```

**Comment by Y4er** [comment]
thanks,it's work.

before 

![image](https://user-images.githubusercontent.com/40487319/168516767-1c857a48-3a33-42f0-9020-f9c8e557c292.png)

after

![image](https://user-images.githubusercontent.com/40487319/168516814-54b0e277-eb1b-4036-81e7-6353185891c3.png)

Recommend all friends hosted on vercel to remove the [pwa] block from params.toml.

**Comment by razonyang** [comment]
@Y4er  FYI, The theme won't precache the static images since [v1.0.0-alpha.2](https://github.com/razonyang/hugo-theme-bootstrap/releases/tag/v1.0.0-alpha.2), it precaches only the required JS, CSS and pages that used for offline pages.
You can also precache custom resources, such as fonts, images, pages, styles and scripts, please check out the [PWA Precache](https://hbs.razonyang.com/v1/en/docs/pwa/#precache) for details.

**Comment by Y4er** [comment]
Nice job!
